- rid: "ri.language-model-service..language-model.anthropic-claude-3-7-sonnet"
- rid: "ri.language-model-service..language-model.gpt-4-o"
- rid: "ri.language-model-service..language-model.text-embedding-3-large_azure"
