package:
  name: langchain-palantir
  version: 0.0.4
source:
  path: ../src
requirements:
  build:
  - python
  - setuptools
  run:
  - palantir_models
  - langchain
  - langchain-core
  - pytest
  - python
  - langchain-openai
test:
  requires:
  - pytest
  - pytest-transforms
  - pytest-randomly
build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python
