package:
  name: langchain-palantir
  version: 0.0.8
source:
  path: ../src
requirements:
  build:
  - python>=3.12.10
  - setuptools
  run:
  - langchain-core
  - python>=3.12.10
  - palantir_models
  - language-model-service-api
test:
  requires:
  - pytest
  - pytest-transforms
  - pytest-randomly
  - ruff
build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python
