package:
  name: '{{ PACKAGE_NAME }}'
  version: '{{ PACKAGE_VERSION }}'
source:
  path: ../src
requirements:
  build:
  - python
  - setuptools
  run:
  - python
  - palantir_models
  - langchain
  - langchain-core
test:
  requires:
  - pytest
  - pytest-transforms
build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python
