package:
  name: langchain-palantir
  version: 0.0.9
source:
  path: ../src
requirements:
  build:
  - python>=3.11.10
  - setuptools
  run:
  - python>=3.11.10
  - langchain-core>=1.0.0
  - language-model-service-api
  - palantir_models
test:
  requires:
  - pytest
  - ruff
  - langchain>=1.0.0
build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python
